# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js 18 image as the base image for building
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the project
RUN npm run build

# Use a smaller Node.js image for the final image
FROM node:18-slim

# Set the working directory
WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# Copy the .env.example to .env and instruct users to edit it with their API key
COPY .env.example .env

# Inform Docker that the container listens on port 80
EXPOSE 80

# Set the environment variable to ensure .env is used
ENV NODE_ENV=production

# Define the command to run the application
CMD ["node", "build/index.js"]